const GLOSSARY_DATA = [
  { term: "Phishing", def: "A social engineering attack where attackers impersonate trusted entities to trick victims into revealing sensitive information." },
  { term: "Ransomware", def: "Malicious software that encrypts a victim's files and demands payment for the decryption key." },
  { term: "Zero-Day", def: "A vulnerability unknown to the software vendor, exploited before a patch is available." },
  { term: "DDoS", def: "Distributed Denial of Service — overwhelming a target with traffic from multiple sources to disrupt service." },
  { term: "Malware", def: "Umbrella term for malicious software including viruses, worms, trojans, ransomware, and spyware." },
  { term: "SQL Injection", def: "An attack technique that inserts malicious SQL code into input fields to manipulate database queries." },
  { term: "XSS (Cross-Site Scripting)", def: "An injection attack where malicious scripts are injected into trusted websites and executed in victims' browsers." },
  { term: "Brute Force Attack", def: "Systematically trying every possible password combination until the correct one is found." },
  { term: "Social Engineering", def: "Psychological manipulation techniques used to trick people into divulging confidential information." },
  { term: "Botnet", def: "A network of compromised computers controlled remotely by an attacker, often used for DDoS or spam." },
  { term: "Man-in-the-Middle (MITM)", def: "An attack where the attacker secretly intercepts and possibly alters communication between two parties." },
  { term: "Penetration Testing", def: "Authorized simulated cyberattack on a system to evaluate its security posture." },
  { term: "CVE", def: "Common Vulnerabilities and Exposures — a standardized identifier for publicly known security vulnerabilities." },
  { term: "Two-Factor Authentication (2FA)", def: "A security process requiring two different authentication factors to verify identity." },
  { term: "Firewall", def: "A network security device that monitors and filters incoming/outgoing traffic based on security rules." },
  { term: "Encryption", def: "The process of converting data into a coded format to prevent unauthorized access." },
  { term: "Spear Phishing", def: "A targeted phishing attack aimed at a specific individual or organization, often using personalized information." },
  { term: "Trojan Horse", def: "Malware disguised as legitimate software that performs malicious actions once installed." },
  { term: "Worm", def: "Self-replicating malware that spreads across networks without requiring user interaction." },
  { term: "Keylogger", def: "Software or hardware that records keystrokes to capture sensitive information like passwords." },
  { term: "Honeypot", def: "A decoy system designed to attract and detect attackers, used for threat intelligence gathering." },
  { term: "Patch Management", def: "The process of acquiring, testing, and installing software updates to fix vulnerabilities." },
  { term: "Threat Intelligence", def: "Information about current and potential cyber threats used to make informed security decisions." },
  { term: "Endpoint Detection and Response (EDR)", def: "Security tools that monitor endpoint devices for suspicious activity and respond to threats." },
  { term: "WHOIS", def: "A protocol used to query databases storing registered domain name and IP address ownership information." },
  { term: "Incident Response", def: "The organized approach to addressing and managing the aftermath of a security breach or attack." },
  { term: "Vulnerability Assessment", def: "The process of identifying, quantifying, and prioritizing security weaknesses in a system." },
  { term: "Credential Stuffing", def: "Using stolen username/password pairs from one breach to attempt login on other unrelated services." },
  { term: "Sandboxing", def: "Running untrusted code in an isolated environment to observe behavior without risking the host system." },
  { term: "SSL/TLS", def: "Cryptographic protocols that provide secure, encrypted communication over a computer network." }
];
