const NEWS_DATA = [
  { title: "Critical Zero-Day Exploit Found in Popular VPN Software", category: "vulnerability", summary: "Security researchers disclosed a critical RCE vulnerability affecting millions of enterprise VPN endpoints worldwide.", source: "ThreatPost", time: "2h ago" },
  { title: "Major Healthcare Provider Suffers Ransomware Attack", category: "ransomware", summary: "A ransomware gang claims to have exfiltrated 3TB of patient records before encrypting hospital systems across 12 states.", source: "BleepingComputer", time: "4h ago" },
  { title: "New Phishing Campaign Targets Microsoft 365 Users", category: "phishing", summary: "Attackers are using fake login pages mimicking Office 365 to harvest credentials from corporate employees.", source: "KrebsOnSecurity", time: "6h ago" },
  { title: "Banking Trojan Spreads via Fake Browser Updates", category: "malware", summary: "A new banking trojan disguises itself as a Chrome update notification to steal financial credentials.", source: "SecurityWeek", time: "8h ago" },
  { title: "Data Breach Exposes 50 Million User Records", category: "breach", summary: "An e-commerce platform confirms a breach affecting customer names, emails, and partial payment information.", source: "HackerNews", time: "10h ago" },
  { title: "Critical Flaw in Apache Log4j Variant Discovered", category: "vulnerability", summary: "A new vulnerability similar to Log4Shell affects logging libraries used across thousands of Java applications.", source: "CISA", time: "12h ago" },
  { title: "Ransomware Group Targets Critical Infrastructure", category: "ransomware", summary: "Energy sector companies warned of increased ransomware targeting following recent supply chain compromises.", source: "CISA", time: "1d ago" },
  { title: "Spear Phishing Attack Targets C-Suite Executives", category: "phishing", summary: "Highly targeted phishing emails impersonating board members request urgent wire transfers.", source: "Dark Reading", time: "1d ago" },
  { title: "New Android Malware Bypasses Play Store Security", category: "malware", summary: "Malicious apps disguised as utility tools have been downloaded over 2 million times before removal.", source: "Malwarebytes", time: "1d ago" },
  { title: "Government Database Breach Affects Millions of Citizens", category: "breach", summary: "A misconfigured cloud database exposed sensitive citizen data for over 8 months before discovery.", source: "Reuters", time: "2d ago" },
  { title: "Critical SQL Injection Found in Popular CMS Platform", category: "vulnerability", summary: "Millions of websites at risk after researchers discover unpatched SQL injection vulnerability in widely-used CMS.", source: "PortSwigger", time: "2d ago" },
  { title: "Supply Chain Attack Compromises Software Update Mechanism", category: "malware", summary: "Threat actors injected malicious code into a legitimate software update, affecting downstream customers.", source: "Wired", time: "3d ago" }
];
